mysql:
  image: mysql/mysql-server
  container_name: mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=blog

haproxy:
  env_file: local.env
  image: haproxy
  container_name: haproxy-api
  volumes:
    - "/vagrant/etc/haproxy:/usr/local/etc/haproxy"
  expose:
    - 80
  ports:
    - "9090:80"